#include <iostream>

int getUserInput()
{
    int x;
    std::cout << "Enter the value:";
    std::cin >> x;
    return x;

}

int calculateForce(int mass, int acceleration)
{
    return mass * acceleration;
}

int main()
{
    int mass, acceleration;
    std::cout << "Hello, today we're going to calculate Force by F = ma" << std::endl;
    std::cout << "First we're going to need the mass(In kg)" << std::endl;
    mass = getUserInput();
    std::cout << "Next we will need the acceleration of the object (Assuming constant)(In m/s^2)" << std::endl;
    acceleration = getUserInput();
    std::cout << "The force generated by this object is " << calculateForce(mass, acceleration) << " Newtons" << std::endl;

    return 0;
}

